### ISSUE TITLE
资源冲突了

### ISSUE THREAD

**Issue by hudan2714** [smuyyh/ImageSelector#107]
is also present at [com.yuyh.imgsel:library:2.0.2] AndroidManifest.xml:33:17-55 value=(@xml/provider_paths).
  	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

**Comment by smuyyh** [comment]
把这句加在你的mainfest试试  tools:replace="android:resource
