### ISSUE TITLE
provider跟bugly 的 provider冲突

### ISSUE THREAD

**Issue by 675915408** [smuyyh/ImageSelector#114]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by 675915408** [comment]
用您的怕bugly的 7.0下载功能不能用了。

**Comment by changoal** [comment]
我也遇到了这个问题

**Comment by smuyyh** [comment]
升级到新版本，我记得这个解决过了。

**Comment by changoal** [comment]
好的，更新之后可以了

**Comment by ArcherLucky** [comment]
知道为什么了，解决了new一个FileProvider文件的问题，如果用默认的v4.provider还有这个问题
