### ISSUE TITLE
内存泄露了？

### ISSUE THREAD

**Issue by lihuanming** [smuyyh/ImageSelector#116]
内存泄露了？

**Comment by feisher** [comment]
好像确实有内存泄漏问题，` ISNav.getInstance().init(new ImageLoader() {
            @Override
            public void displayImage(Context context, String path, ImageView imageView) {
                Glide.with(context).load(path).into(imageView);
            }
        });`上下文无法回收

**Comment by smuyyh** [comment]
这个一般用全局application就好了。注册一次

**Comment by evansherry** [comment]
@smuyyh 你这个泄漏确实存在，Glide推荐使用Activity作为Context，你将Config作为一个静态变量，而它持有了ImageLoader这个对象，而这个对象又持有Activity对象，导致Activity无法回收，这是个很严重的问题
