### ISSUE TITLE
华为Mate8  不裁剪拍摄会报空

### ISSUE THREAD

**Issue by bertsir** [smuyyh/ImageSelector#117]
RT

**Comment by bertsir** [comment]
试了一下 别的机型也会  代码定位到了
 if (tempPhotoFile != null) {
                    if (config.needCrop) {
                        crop(tempPhotoFile.getAbsolutePath());
                    } else {
                        **complete(new Image(cropImageFile.getPath(), cropImageFile.getName()));**
                    }
                }

**Comment by rcj60560** [comment]
我也遇到了这个问题 跟你一样报空指针，就是这里

**Comment by rcj60560** [comment]
@smuyyh 麻烦看到回一下 谢谢

**Comment by rcj60560** [comment]
@bertsir 请问你解决了吗 麻烦看到回我一下 谢谢

**Comment by bertsir** [comment]
我直接改的代码complete(new Image(tempPhotoFile.getPath(), tempPhotoFile.getName()));

**Comment by bertsir** [comment]
@rcj60560

**Comment by smuyyh** [comment]
V2.0.3 已解决。
