### ISSUE TITLE
拍照不剪切报空指针异常

### ISSUE THREAD

**Issue by jianghaijun** [smuyyh/ImageSelector#137]
android版本：7.1 红米note 4x
引用：
ISCameraConfig config = new ISCameraConfig.Builder()
                .needCrop(false) // 裁剪
                //.cropSize(1, 1, 1200, 1200)
                .build();
ISNav.getInstance().toCameraActivity(mContext, config, 1);

异常：
![image](https://user-images.githubusercontent.com/17917912/41952536-ffeb33c0-7a02-11e8-81d1-e665ba0389f5.png)

**Comment by smuyyh** [comment]
之前修复过了，更新一下版本吧~~
