### ISSUE TITLE
选择图片无法预览是怎么回事，三星平板，OPPO手机测试过

### ISSUE THREAD

**Issue by shoulderdh** [smuyyh/ImageSelector#139]
![image](https://user-images.githubusercontent.com/14287365/42418206-efcf76c6-82cd-11e8-8704-a276fa48efe5.png)
![image](https://user-images.githubusercontent.com/14287365/42418221-3b845a96-82ce-11e8-826e-fef04148f503.png)
使用时候，点击选择图片，预览显示不出列表图片，点击空白图，能返回正常图片，请问一下是什么原因吗？
使用代码如下：

` ISListConfig config1 = new ISListConfig.Builder()
                        .multiSelect(false)
                        .btnText("确定")
                        .btnTextColor(Color.WHITE)
                        .title("选择背景图片")
                        .statusBarColor(getResources().getColor(R.color.themeColor))
                        .titleBgColor(getResources().getColor(R.color.themeColor))
                        .titleColor(Color.WHITE)
                        .allImagesText("所有图片")
                        .needCamera(true)
                        .build();
                ISNav.getInstance().toListActivity(this, config1, PHOTO_REQUEST_CODE);`

**Comment by smuyyh** [comment]
ImageLoader 没设置吧？
