### ISSUE TITLE
现在只支持v4包的fragment和activity跳转吗？普通包下的fragment跳转没反应,我看判断只判断了两种类型

### ISSUE THREAD

**Issue by ConanHolmes** [smuyyh/ImageSelector#144]

**Comment by ConanHolmes** [comment]
`public void toListActivity(Object source, ISListConfig config, int reqCode) {
        if (source instanceof Activity) {
            ISListActivity.startForResult((Activity) source, config, reqCode);
        } else if (source instanceof Fragment) {
            ISListActivity.startForResult((Fragment) source, config, reqCode);
        }
    }`

**Comment by smuyyh** [comment]
增加了 android.app.Fragmebt    V2.0.6
