### ISSUE TITLE
导入依赖manifest中fileprovider冲突

### ISSUE THREAD

**Issue by HandsomeBoy11** [smuyyh/ImageSelector#146]
最好自定义个fileprovider

**Comment by smuyyh** [comment]
这个之前改了呀，你用的是什么版本的呢

**Comment by z896872021** [comment]
> 这个之前改了呀，你用的是什么版本的呢

我也遇到了这个问题,用的是2.06,然后,使用的自定义的fileprovide,我自己的manifest 总

**Comment by HandsomeBoy11** [comment]
> > 这个之前改了呀，你用的是什么版本的呢
> 
> 我也遇到了这个问题，用的是2.06，然后，使用的自定义的fileprovide，我自己的manifest总

我导入了图片库moudle  就只需要改一下图片库的manifest中的fileprovide  自己重新定义一个就可以，如果不自己定义一个就会和项目中已有的fileprovide重名  就冲突了

**Comment by z896872021** [comment]
> 最好自定义个fileprovider

我使用的就是自定义，还是不行

**Comment by z896872021** [comment]
> 这个之前改了呀，你用的是什么版本的呢

2.06的
