### ISSUE TITLE
按照教程导入项目后，无法使用？

### ISSUE THREAD

**Issue by faithHyperion** [smuyyh/ImageSelector#152]

**Comment by WANG1020** [comment]
java.lang.NoSuchMethodError: No virtual method load(Ljava/io/File;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.ureading.test1-1/base.apk)
        at com.yongchun.library.adapter.ImageListAdapter.onBindViewHolder(ImageListAdapter.java:97)
