### ISSUE TITLE
记录选中位子

### ISSUE THREAD

**Issue by wangchen0338** [smuyyh/ImageSelector#158]
记录选中5张，然后删除图片其中一张,怎么更新选中记录，现在再次进去还是记录选中5张的

**Comment by smuyyh** [comment]
Constant.imageList

**Comment by wangchen0338** [comment]
谢谢,后来看你的源码自己找到了,顺带提个建议,就是查看图片时能不能增加缩放功能,毕竟有些时候需要此功能
