### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by Hy-Wang777** [smuyyh/ImageSelector#162]
Class 'com.yuyh.library.imgsel.ui.ISListActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/net.chejieren.android.debug-RqCZLB9Ui7HyoOhIsYS4ZQ==/base.apk!classes2.dex)

**Comment by smuyyh** [comment]
androidx没适配？
