### ISSUE TITLE
Android N 调用相册裁剪时会报错 crash- FileUriExposedException

### ISSUE THREAD

**Issue by 1CD1** [smuyyh/ImageSelector#17]
leryFinal/IMG_20161018180127.jpg typ=image/\* cmp=com.google.android.apps.photos/.photoeditor.intents.EditActivity (has extras)} from uid 10088 on display 0
10-18 19:09:16.143   856  4000 I ActivityManager: Start proc 2477:com.google.android.apps.photos/u0a74 for activity com.google.android.apps.photos/.photoeditor.intents.EditActivity
10-18 19:09:16.498   856 20383 W ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=2477, uid=10074 that is not exported from uid 10071
10-18 19:09:16.625  2477  2477 E AndroidRuntime: FATAL EXCEPTION: main
10-18 19:09:16.625  2477  2477 E AndroidRuntime: Process: com.google.android.apps.photos, PID: 2477
10-18 19:09:16.625  2477  2477 E AndroidRuntime: android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/RxGalleryFinal/IMG_20161018180127.jpg exposed beyond app through Intent.getData()
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.net.Uri.checkFileUriExposed(Uri.java:2346)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.content.Intent.prepareToLeaveProcess(Intent.java:8933)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.app.Activity.startActivityForResult(Activity.java:4224)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at cr.startActivityForResult(PG:48)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at cw.startActivityForResult(PG:75)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at tsq.startActivityForResult(PG:175)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at android.app.Activity.startActivityForResult(Activity.java:4183)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at cw.startActivityForResult(PG:871)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at tsq.startActivityForResult(PG:167)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at rpd.a(PG:1093)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at jow.a(PG:7349)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at rsx.a(PG:409)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at rtj.a(PG:316)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at rtk.run(PG:1026)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at uwd.run(PG:95)
10-18 19:09:16.625  2477  2477 E AndroidRuntime:    at rth.run(PG:1284)

**Comment by smuyyh** [comment]
Android N以上 貌似要把file:// 换成 content://

**Comment by 1CD1** [comment]
在哪里改？我用的是lib，没有用source

**Comment by smuyyh** [comment]
直接依赖是吧，那没法改。不然就先源码拉下来  没几个文件

**Comment by SilentWolf1993** [comment]
Android N改用FileProvider了。。

**Comment by feisher** [comment]
现在这个问题解决了吗？

**Comment by smuyyh** [comment]
@feisher 目前我在7.1.1上试  是没问题的。

**Comment by feisher** [comment]
@smuyyh 已经找到解决办法了，用23的API就行了。主要还是24的API导致的 ，设置 compileSdkVersion 23  就好了

**Comment by smuyyh** [comment]
@feisher 改了。compileSdkVersion  24 也支持。V1.3.6
