### ISSUE TITLE
FileProvider 报错，解决办法内详

### ISSUE THREAD

**Issue by llfnqt** [smuyyh/ImageSelector#172]
步骤一：自定义provider_paths.xml，并放入xml文件夹中，xml内容如下：

<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <root-path
        path=""
        name="camera_photos" />
    <external-path name="external_storage_root" path="." />
    <external-path name="external_storage_download" path="Download" />
</paths>

步骤二：AndroidManifest.xm 里面声明加上如内容，直接复制即可：

        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="android:resource"/>
        </provider>

搞定，希望能帮到大家

**Comment by smuyyh** [comment]
fixed
