### ISSUE TITLE
大佬，适配一下android11分区存储

### ISSUE THREAD

**Issue by baihanbing** [smuyyh/ImageSelector#173]

**Comment by lanyueyin** [comment]
同样需要适配Android11分区存储

**Comment by fallenstardust** [comment]
同求适配Android11分区存储

**Comment by smuyyh** [comment]
好的。

**Comment by smuyyh** [comment]
@fallenstardust @lanyueyin @baihanbing 具体需求问题是什么呢？

**Comment by Zhupro** [comment]
大佬，目前在Android 11系统下 选择完图片会提示 保存时发生错误，保存失败。拍照图片会提示图片加载失败。推测可能是图片路径有问题找不到图片，劳烦大佬尽快解决一下。十分感谢

**Comment by fallenstardust** [comment]
![image](https://user-images.githubusercontent.com/10228030/96818366-f75f6f80-1453-11eb-8f7e-df95b109f5fc.png)同上，这是我抓到的e

**Comment by smuyyh** [comment]
> 大佬，目前在Android 11系统下 选择完图片会提示 保存时发生错误，保存失败。拍照图片会提示图片加载失败。推测可能是图片路径有问题找不到图片，劳烦大佬尽快解决一下。十分感谢

我 Android 11 试了选择和拍照没问题，就是 crop 有问题。

**Comment by fallenstardust** [comment]
是的，我这里就用了您的裁剪。安卓11下无法通过裁剪到cache，glide就找不到图片

**Comment by Zhupro** [comment]
@smuyyh 是的大佬，我这边也是用了裁剪功能。

**Comment by smuyyh** [comment]
@fallenstardust @Zhupro 裁剪的问题是因为android11无法访问其他应用的缓存目录，裁剪是系统应用，我今天修复一下。

**Comment by Zhupro** [comment]
@smuyyh 受教了，感谢感谢～

**Comment by fallenstardust** [comment]
有劳大佬适配，万分感谢

**Comment by smuyyh** [comment]
2.1.0 已修复。
