### ISSUE TITLE
选择器里的图片不显示

### ISSUE THREAD

**Issue by keaidefeizao** [smuyyh/ImageSelector#177]
有图片，也能选择土拍你，但不显示图像。

**Comment by smuyyh** [comment]
展示是外部提供的imageloader做的。

**Comment by keaidefeizao** [comment]
> [图像加载器]

不不不，我说的是在选择器里的图片不显示缩略图。

**Comment by oscarliusy** [comment]
我也遇到了，启动选择器后，图片只有统一的占位背景，没有各自的缩略图。但是点击占位图可以进入编辑页面
