### ISSUE TITLE
TitleBar左边的返回按钮，能否点击？

### ISSUE THREAD

**Issue by max8888888** [smuyyh/ImageSelector#2]
TitleBar左边有个返回按钮，能不能设置这个按钮的点击事件？最起码直接finish()也行啊~

**Comment by max8888888** [comment]
对于将代码上传到JCenter上，我表示高度感谢！这样使用起来太方便了，真心不喜欢导入一个module。所以还是希望作者能够更新一下

**Comment by smuyyh** [comment]
哈哈。忘了加上了~   马上加。

**Comment by smuyyh** [comment]
可以了。compile 'com.yuyh.imgsel:library:1.0.3'

**Comment by max8888888** [comment]
这么高效率……   5星好评！ 哈哈~

**Comment by starsight** [comment]
手动感谢~

**Comment by starsight** [comment]
求返回按钮用原声的那种，或者加个选择项。。感谢

**Comment by smuyyh** [comment]
@starsight 原生？你是说 <— ？

**Comment by starsight** [comment]
@max8888888 嗯嗯，感觉那种看的习惯些

**Comment by smuyyh** [comment]
@starsight  
compile 'com.yuyh.imgsel:library:1.1.0'
增加自定义返回按钮图标及配置沉浸式状态栏选项

**Comment by starsight** [comment]
@smuyyh THX
