### ISSUE TITLE
在调用相机的时候报错

### ISSUE THREAD

**Issue by JianJianZhang** [smuyyh/ImageSelector#20]
请问一下，错误信息提示没有打开摄像头的权限，单独写一个demo ,又没有这样的问题。集成到项目中，就提示没有权限的问题，这个怎么解决啊？

**Comment by smuyyh** [comment]
系统版本多少？>=6.0？  相机权限和SD权限加了  应该是没问题了

**Comment by JianJianZhang** [comment]
系统是6.0的华为荣耀，权限也加了。我单独写个demo,试了一下，没有问题。就是放在项目中，报错没有权限

**Comment by smuyyh** [comment]
target 为23的话需要单独申请权限。你的demo如果target小于23  可以不用申请权限，可能你的项目是23或24

**Comment by JianJianZhang** [comment]
demo的target也是大于23的，看了一下你的源码中，不是已经动态的申请权限了吗？

**Comment by JianJianZhang** [comment]
那我需要在你的源码中改，还是一开始就申请这个权限呢？

**Comment by smuyyh** [comment]
有点久了  都忘记有申请权限这回事了。如果报没权限那肯定就是权限请求没起来，或者第一次调用的时候给人家拒绝掉了。申请权限应该是没问题，你可以到系统设置里面看看，权限是不是被屏蔽了。

**Comment by JianJianZhang** [comment]
帮我看一下，在imgSelFragement中这样修改是不是对的？
         if (config.needCamera && position == 0) {
                    if (ContextCompat.checkSelfPermission(getContext(), Manifest.permission.CAMERA)
                            != PackageManager.PERMISSION_GRANTED) {
                        ActivityCompat.requestPermissions(getActivity(),
                                new String[]{Manifest.permission.CAMERA},
                                CAMERA_REQUEST_CODE);
                    } else {
                        showCameraAction();
                    }

 @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        switch (requestCode) {
            case CAMERA_REQUEST_CODE:
                if (permissions[0].equals(Manifest.permission.CAMERA) && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    showCameraAction();
                } else {
                    Toast.makeText(getContext(), getString(R.string.permission_denied),                Toast.LENGTH_SHORT).show();
                }
                break;
        }

        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

**Comment by JianJianZhang** [comment]
麻烦了

**Comment by smuyyh** [comment]
格式有点乱...   看起来没啥问题。请求其实也简单啊，就两步
1、ContextCompat.checkSelfPermission 请求权限
2、onRequestPermissionsResult 接收权限处理回调。
跟startActivityForResult 没啥两样
