### ISSUE TITLE
4.4及以下版本图库界面顶部标题栏被StatusBar覆盖

### ISSUE THREAD

**Issue by husang-cx** [smuyyh/ImageSelector#21]
把兼容用的StatusBarCompat.compat(this, config.statusBarColor);注释掉后 6.0和4.4.4系统都显示正常

**Comment by smuyyh** [comment]
我记得好像有处理4.4以下的呀  太久了有点忘了  等下有空来看看

**Comment by smuyyh** [comment]
@husang-cx 你是在什么版本测的。我用4.0  没发现这个问题呀~

**Comment by husang-cx** [comment]
4.4.4版本 @smuyyh

**Comment by smuyyh** [comment]
不好意思 前阶段比较忙  没来得及处理。我昨天改了，改之前确实在4.4.4有问题  不过我好像也没改沉浸式的  略奇怪  今天用了好多个4.4.4的机型测了  都没问题。 可以的话帮忙再试试~ 谢谢 更新了。
