### ISSUE TITLE
选择图片后在页面加载，然后删除加载的图片如何才能让库里的图片也删除同一张图片

### ISSUE THREAD

**Issue by liuxiting** [smuyyh/ImageSelector#24]

**Comment by smuyyh** [comment]
手动去操作Constant.imgList

**Comment by liuxiting** [comment]
imgList是我自己定义的那个list还是库里的，我意思是当我的布局加载的图片删除一个以上图片，当再次进入选择图片的库操作界面时刷新库的选择的图片。以保证和我页面图片保持一致

**Comment by smuyyh** [comment]
库里面的。去操作这个对象就可以了  Constant.imgList 用于保存选中 的图片，remove掉

**Comment by liuxiting** [comment]
Constant.imageList=listpath;这样写吗，listpath是我从onActivityResult中取到的图片地址

**Comment by smuyyh** [comment]
最好还是直接remove某个图片url。比如删除的图片url是"/sdcard/xxx.jpg"， 那就Constant.imgList.remove("/sdcard/xxx.jpg");
