### ISSUE TITLE
返回图标的位置有误

### ISSUE THREAD

**Issue by JiangShuLiang** [smuyyh/ImageSelector#25]
如图所示，返回图标应该是在左上角才对。可是运行后位置却偏离了。
感谢作者！
![_20161215032704](https://cloud.githubusercontent.com/assets/20485764/21173270/e827fc6e-c211-11e6-937e-bb9bfc191a9a.png)

**Comment by smuyyh** [comment]
marginLeft="10dp"   不可能这么大啊？  你改了代码没

**Comment by JiangShuLiang** [comment]
关于返回图标的，我只有改动这一处：.backResId(R.drawable.back)

**Comment by JiangShuLiang** [comment]
无论是虚拟机还是真机都是这个样子，返回按钮位置偏离了

**Comment by smuyyh** [comment]
run过demo没？demo不会吧？会不会是图标左边有空白...

**Comment by JiangShuLiang** [comment]
demo没run过。
图片真的确认过了，图片没有半点问题，换成ic_launcher也一样位置偏离。会不会对图片尺寸有要求？

**Comment by JiangShuLiang** [comment]
最新发现是：点击图中返回图标左边的区域，都会触发返回事件。

**Comment by smuyyh** [comment]
这样看起来就是图标占据的位置太大了。  这怪了   有空可以把demo run下试试   我这边没出现这问题

**Comment by JiangShuLiang** [comment]
找到问题了，跟图片的尺寸有关系。我原来的那张会偏离位置的back图片是200*200的，现在改成50*50位置就正常了。

**Comment by JiangShuLiang** [comment]
200x200，50x50。上面尺寸漏了个x号

**Comment by smuyyh** [comment]
嗯解决就好～
