### ISSUE TITLE
确定按钮背景颜色设置无效+一点建议

### ISSUE THREAD

**Issue by JiangShuLiang** [smuyyh/ImageSelector#26]
如图所示，我的确定按钮背景色是设置成跟titleBar一个颜色，可是运行后颜色没发生变化。

建议就是：能否在ImgSelConfig添加一个显示/不显示确定按钮的设置。因为如果是单选模式的话，确定按钮就没必要存在了（因为根本没有按它的机会）

最后，感谢作者！

![_20161215033115](https://cloud.githubusercontent.com/assets/20485764/21173375/61a5f3c0-c212-11e6-8256-c5c33f77d43b.png)

**Comment by JiangShuLiang** [comment]
这个。。。是我太愚了。。。已经解决了。。。
确定按钮的背景色传入的参数不能用Color.xxx，而是要用Color.parseColor("#1296DB")

把确定按钮的背景色设置成和titleBar一个色后，再设置确定按钮的文本为""就可以实现不显示确定按钮了。

是我太疏忽了。不好意思，该issue可以close了

**Comment by smuyyh** [comment]
不设置背景颜色，貌似就是透明的吧？  没必要在设置成titlebar颜色了
