### ISSUE TITLE
裁剪图片界面里的“保存”和“舍弃”button有办法自定义样式吗？

### ISSUE THREAD

**Issue by JiangShuLiang** [smuyyh/ImageSelector#27]
如图，这两个button的样式感觉不是很好看，想问作者有办法自定义样式吗？

![_20161215033917](https://cloud.githubusercontent.com/assets/20485764/21173624/8a1aa502-c213-11e6-9bf9-524b2d19d8cc.png)

**Comment by smuyyh** [comment]
这边调用的是系统的裁剪，没法自定义吧。

**Comment by JiangShuLiang** [comment]
好的，感谢！
