### ISSUE TITLE
在Android 6.0 安装直接崩溃了

### ISSUE THREAD

**Issue by 1900han** [smuyyh/ImageSelector#3]
是不是权限适配的问题

**Comment by 1900han** [comment]
还有问题是每次点击一张图片,其他图片会闪烁,这应该是个bug;选了9张图之后,点击拍照,返回给activity的结果就变成10张了,能不能选足9张,就禁止再拍照

**Comment by smuyyh** [comment]
6.0 权限适配还没加上。 我处理一下~

**Comment by 823546371** [comment]
V1.1.0  6.0权限问题修复好了么

**Comment by smuyyh** [comment]
@823546371 好了。
