### ISSUE TITLE
照相机拍的图片一直存在于已选列表？

### ISSUE THREAD

**Issue by ErebusHu** [smuyyh/ImageSelector#33]
用相机拍的图片 再一次进入图片选择器时 一直存在与已选列表 在图片选择页面既无法查看也无法删掉选中。

**Comment by smuyyh** [comment]
哦对，下版改一下。谢谢提醒～
你现在需要的话可先调用Constants.imgList.cleaer

**Comment by ErebusHu** [comment]
OK~谢谢啦

**Comment by smuyyh** [comment]
@ErebusHu 改了。V1.3.3
