### ISSUE TITLE
Android6.0+ 动态相机权限？

### ISSUE THREAD

**Issue by ErebusHu** [smuyyh/ImageSelector#35]
机型：HUAWEI JDN-W09  系统：Android 6.0.1 API 23
首次进入图片选择界面后
动态提示请求SD卡读写权限 但没有提示请求相机权限

在系统权限设置中看到 相机权限的处理方式是 请求。
在没有把处理方式改成允许之前 点图片选择器中的相机按钮会一直报错。
望解决~ 谢谢

**Comment by ErebusHu** [comment]
在系统权限设置中看到 相机权限的处理方式是 询问。

**Comment by houxg** [comment]
`ImageSelector`只做了磁盘空间的权限申请，没有做相机的。其实权限的问题应该由App自己去做，比如用户就是不想给你相机的权限，那就做退化处理，只显示手机内照片。

**Comment by smuyyh** [comment]
@ErebusHu 之前确实没申请相机权限。这个加一下也快，目前是点击拍照时申请相机权限。V1.3.4
