### ISSUE TITLE
用该库的时候 有黑框 这怎么办

### ISSUE THREAD

**Issue by ideastudios** [smuyyh/ImageSelector#36]
![screenshot_2017-01-12-11-23-51](https://cloud.githubusercontent.com/assets/16684417/21875895/4bd52340-d8ba-11e6-9761-6165742c696c.png)

**Comment by smuyyh** [comment]
不应该呀~  是最新版本么？什么型号手机

**Comment by ideastudios** [comment]
不知为啥  刚开始是ok的 后面就变坏了
