### ISSUE TITLE
关于第一次选择图片后，第二次选择图片限制问题

### ISSUE THREAD

**Issue by mashell** [smuyyh/ImageSelector#42]
我第一次选择三张图片，返回结果后用户删除两张，剩一张，我第二次进去选择图片如何限制用户最多选择八张图片呢

**Comment by smuyyh** [comment]
1. config配置的时候，可以通过.rememberSelected(true)，这个会记住上次选中的图片，手动删除两张的话，对应删除Constant.imageList的图片，可解决这个
2. 重新进入的时候，修改confi，.maxNum(9)  自行改为8之类的..

**Comment by mashell** [comment]
非常感谢 👍
