### ISSUE TITLE
Provider冲突

### ISSUE THREAD

**Issue by dh1021** [smuyyh/ImageSelector#44]
android:authorities="com.yuyh.library.imgsel.provider"这一行冲突了导致app不能安装，我又把你的library下载下来引入到我的工程中并改了上面的名字，又报权限的错误，
java.lang.SecurityException: Uid 10179 does not have permission to uri 0 @ content://com.yuyh.library.imgsel.provider/external_files/Android/data/我的包名/cache/1488597026481.jpg

请问怎么解决？

**Comment by smuyyh** [comment]
你是两个应用同时用了这个麽？如果你直接拉代码，那包名是不是应该改成你应用的包名？

**Comment by dh1021** [comment]
应该是我手机上的其他应用也引用了你的库导致的冲突

**Comment by smuyyh** [comment]
哦  目前确实存在这个问题。 我找找解决办法

**Comment by smuyyh** [comment]
建议你先把targetSdkVersion 调为23或以下。可以去除provider相关的东西，原本改动这个是为了适配7.0的裁剪与拍照。

**Comment by vanzh** [comment]
我的解决方法 ：
AndroidManifest.xnl的<provider>  设置 replace，使meger后的xml文件 采用自己的android:authorities、 android:resource就行，7.0上测试无问题；
参考如下，：
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.skylife.wlha.fileprovider"
            android:grantUriPermissions="true"
            android:exported="false"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource"/>
        </provider>

**Comment by smuyyh** [comment]
V1.3.8 修改android:authorities 动态采用app的applicationId
