### ISSUE TITLE
图片压缩问题

### ISSUE THREAD

**Issue by feisher** [smuyyh/ImageSelector#45]
选择后onActivityResult()里面获取到的图片是原图。有没有方法不用自己再压缩直接获取合适大小的图片（不开裁剪）

**Comment by smuyyh** [comment]
目前没提供这个方法~~

**Comment by chengxuyuan112** [comment]
楼主 你的这个图片选择不压缩图片不显示，而且还会报错oom

**Comment by smuyyh** [comment]
图片显示主要由重写的ImageLoader控制。理论上oom不受本库控制
