### ISSUE TITLE
gradle添加不了1.3.7

### ISSUE THREAD

**Issue by maybea** [smuyyh/ImageSelector#49]
只能添加1.3.5

**Comment by smuyyh** [comment]
我这边试了一下  是可以的。你看是不是网络问题还是？或者clean一下

**Comment by smuyyh** [comment]
AS 偶尔会这样。 clean或者重启一下应该就可以

**Comment by maybea** [comment]
我把liabrary加进来了，不是网络问题，不然怎么能添加1.3.5呢

**Comment by smuyyh** [comment]
就是as有时会出现这种问题。上次也听人说遇到过。本身不是1.3.7的这个问题

**Comment by maybea** [comment]
额，不管它了，  把代码直接拷进来，改起来也方便 - -
