### ISSUE TITLE
使用Picasso加载图片失败

### ISSUE THREAD

**Issue by xiaobailong24** [smuyyh/ImageSelector#50]
代码：
```
// 自定义图片加载器
private ImageLoader loader = new ImageLoader() {
    @Override
    public void displayImage(Context context, String path, ImageView imageView) {
        // TODO 在这边可以自定义图片加载库来加载ImageView，例如Glide、Picasso、ImageLoader等
        Picasso.with(context).load(path).into(imageView);
    }
};
```
将使用方式中的 **Glide** 替换为 **Picasso**，图片显示白屏，但是有边框。
Picasso Version：2.5.2
ImageSelector Version：1.3.7

**Comment by smuyyh** [comment]
demo 用 picasso 试过没？ 这个本身跟这个库是没多大关系的。就是在onBindViewHolder下  通过这个来加载图片而已，ImageSelector本身并不负责图片加载，都是交给ImageLoader处理

**Comment by vanzh** [comment]
如下可正常显示：
Picasso.with(context).load(Uri.fromFile(new File(path))).into(imageView);
7.0的要注意 用FileProviderr

**Comment by xiaobailong24** [comment]
@vanzh 
确实。谢谢啦

**Comment by xiaobailong24** [comment]
@smuyyh 好的，应该是我的问题，跟这个库没关系，谢谢啦。

**Comment by smuyyh** [comment]
嗯呢  可以就好~~ :smile:
