### ISSUE TITLE
这个库导致改applicationId后 无法安装多个同样的app，好像连引用了该库的不同app也无法同时安装

### ISSUE THREAD

**Issue by 445759814** [smuyyh/ImageSelector#51]

**Comment by smuyyh** [comment]
这是因为ovider冲突的问题。要嘛就是拉源码下来改一下AndroidMainfest，或者参考一下#44

**Comment by 445759814** [comment]
问题解决了，改自己App的AndroidMainfest。但是要从根源解决，你的库应该改一下。如果不同公司的开发者引用了，用户手机都要装他们的App，也会出现这种问题，而且很难排查。

**Comment by smuyyh** [comment]
嗯呢。 下个版本改一下~

**Comment by smuyyh** [comment]
V1.3.8 这个问题解决了。有需要可以试试~~
