### ISSUE TITLE
demo上都有，可是我直接调用时不会出现拍照的按钮。

### ISSUE THREAD

**Issue by StannyBing** [smuyyh/ImageSelector#53]
我采用的是recyclerView.init(this,MultiPickResultView.ACTION_SELECT,null);
因为我需要在界面上出现选择后的图片。但是这么使用，进入相册后，第一张图片不是拍照的功能按钮，而只是全部的照片列表，但是我看你的demo上，就有出现。请问，该怎么解决呢

**Comment by smuyyh** [comment]
// 自由配置选项
ImgSelConfig config = new ImgSelConfig.Builder(context, loader)
        // 是否多选, 默认true
        .multiSelect(false)
        // 是否记住上次选中记录, 仅当multiSelect为true的时候配置，默认为true
        .rememberSelected(false)
        // “确定”按钮背景色
        .btnBgColor(Color.GRAY)
        // “确定”按钮文字颜色
        .btnTextColor(Color.BLUE)
        // 使用沉浸式状态栏
        .statusBarColor(Color.parseColor("#3F51B5"))
        // 返回图标ResId
        .backResId(android.support.v7.appcompat.R.drawable.abc_ic_ab_back_mtrl_am_alpha)
        // 标题
        .title("图片")
        // 标题文字颜色
        .titleColor(Color.WHITE)
        // TitleBar背景色
        .titleBgColor(Color.parseColor("#3F51B5"))
        // 裁剪大小。needCrop为true的时候配置
        .cropSize(1, 1, 200, 200)
        .needCrop(true)
        // 第一个是否显示相机，默认true
        .needCamera(false)
        // 最大选择图片数量，默认9
        .maxNum(9)
        .build();

needCamera(true) 就可以
