### ISSUE TITLE
有内存漏泄

### ISSUE THREAD

**Issue by vanzh** [smuyyh/ImageSelector#54]
* com.skylife.wlha.ui.appenos.AppenosAddActivity has leaked:
* GC ROOT static com.yuyh.library.imgsel.common.Constant.config
* references com.yuyh.library.imgsel.ImgSelConfig.loader
* references com.skylife.wlha.ui.base.MvpCompatActivity$6.this$0 (anonymous implementation of com.yuyh.library.imgsel.ImageLoader)
* leaks com.skylife.wlha.ui.appenos.AppenosAddActivity instance

* Retaining: 77 KB.
* Reference Key: 9265b314-9d0f-46db-88cb-3fd96055a2c2
* Device: HUAWEI honor FRD-AL10 FRD-AL10
* Android Version: 7.0 API: 24 LeakCanary: 1.4 6b04880
* Durations: watch=5006ms, gc=184ms, heap dump=1961ms, analysis=86806ms

**Comment by smuyyh** [comment]
config是static变量没错，原本是想让他可以复用。想想还是把它置空吧。
