### ISSUE TITLE
没有兼容 Android 7.0

### ISSUE THREAD

**Issue by apkcoder** [smuyyh/ImageSelector#56]
if (VERSION.SDK_INT <= VERSION_CODES.M){
                    uri = Uri.fromFile(takeImageFile);
                }else{
                    /**
                     * 7.0 调用系统相机拍照不再允许使用Uri方式，应该替换为FileProvider
                     * 并且这样可以解决MIUI系统上拍照返回size为0的情况
                     */
                    uri = FileProvider.getUriForFile(activity, ProviderUtil.getFileProviderName(activity), takeImageFile);
                }

http://www.cnblogs.com/liushilin/p/6602364.html?utm_source=tuicool&utm_medium=referral

**Comment by smuyyh** [comment]
你这是什么版本的~  挺早之前就适配7.0了...

**Comment by apkcoder** [comment]
恩，看博客用的1.1.0版本。用了1.3.8版本没问题了。但是出现一个新问题。跳转到系统相册页面的时候，相册缩略图全部不显示，都是一个个白块。权限也都加了。也对比了代码，在4.4，6.0，7.0的手机都试了，都不能显示，实在不知道为什么。

**Comment by smuyyh** [comment]
自己写的？

**Comment by apkcoder** [comment]
不是，全部调用你的。

**Comment by smuyyh** [comment]
Demo 试过么~~ 看看行不行

**Comment by apkcoder** [comment]
终于知道为什么了。我换成了Picasso。实在没想到会是这个导致，很奇葩的感觉。我把 demo 的也换成了Picasso加载图片，相册也都显示了，你可以复现试试。
private ImageLoader loader = new ImageLoader() {
        @Override
        public void displayImage(Context context, String path, ImageView imageView) {
            Picasso.with(context).load(path).into(imageView);
        }
    };

**Comment by smuyyh** [comment]
Picasso: Picasso.with(context).load(Uri.fromFile(new File(path))).into(imageView);
