### ISSUE TITLE
拍照后config被重置了

### ISSUE THREAD

**Issue by ganshenml** [smuyyh/ImageSelector#58]
首先感谢提供代码。
一开始在oncreate中设置的是多选，点击拍照后返回当前页再进入页面就变成单选了；
另外：能否开放自定义拍照的样式，白色背景有点刺眼。

还有就是很多人提到的图片缩放的问题，这个可以依赖于其他组件也应该不错。
[https://github.com/bm-x/PhotoView](url)

**Comment by smuyyh** [comment]
有拍照的话  默认就强制更改为单选。因为拍完不好再回到列表页继续选

**Comment by ganshenml** [comment]
@smuyyh 不是拍完照返回图片的列表页再去选择，而是拍完照获取到了图片，用户再次点击去选择图片——>这个时候设置为多选是无效的。

**Comment by smuyyh** [comment]
你前后用的是同一个config对象？可以重新创建config，或更改多选属性。

**Comment by ganshenml** [comment]
@smuyyh 已经再次更改为多选属性了，但是无效的

**Comment by smuyyh** [comment]
我这边试了一下，拍完照退出后，重新进入，依然是可以多选的。

**Comment by smuyyh** [comment]
已修复。
