### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by lpslpsl** [smuyyh/ImageSelector#59]
似乎会长久的持有context对象。然后选择完成或者取消选择的时候没能释放。知道activity退出才能释放

**Comment by smuyyh** [comment]
有内存泄露检测么？具体是哪个持有的

**Comment by lpslpsl** [comment]
没能检测到的说。这个我感觉不算泄露。只是用完没有释放，然后等到外边的activity销毁才一并释放了内存

**Comment by lpslpsl** [comment]
leakcanary检测到是因为common包下面的Constant中的config造成的然后涉及到ImgSelConfig.loader
