### ISSUE TITLE
图片加载错乱

### ISSUE THREAD

**Issue by chenxiaojin** [smuyyh/ImageSelector#6]
当图片数量过多时， 上下滑动， 会出现图片加载错乱问题。比如最后一张图片显示总是不一样， 应该是复用机制导致的问题， 不知道怎么解决。

**Comment by smuyyh** [comment]
是指乱序还是？

**Comment by chenxiaojin** [comment]
@smuyyh 实际顺序没有问题， 是显示问题。 同一个位置的图片会显示不同的图片。重现步骤是有多张图片，我这测试是288张， 上下快速滚动， 就会出现这个问题。应该是imageview复用问题。

**Comment by smuyyh** [comment]
好的。我再试试~

**Comment by chenxiaojin** [comment]
![image](https://cloud.githubusercontent.com/assets/9512516/17915923/16b1204e-69e1-11e6-91fe-0c390021be25.gif)
录制了个图 效果不是很好。 可以看到， 两次滑到底部显示的图片都不一样

**Comment by smuyyh** [comment]
刚试了一下，好像没发现有这个问题呀...  奇怪了。

**Comment by chenxiaojin** [comment]
@smuyyh 我上传了一些我的图片， 280多个风景图片， http://pan.baidu.com/s/1eS4ZfbG 
你下载后放手机试试看。确实是有这个问题， 要上下滚动， 范围也要稍微大点， 我找了其他的库也有这个问题。

早上从glide 的github看到， 也有人反馈有这个问题。 加载图片的时候加上下面这句可以解决：
.diskCacheStrategy(DiskCacheStrategy.SOURCE)

但是加载速度会慢很多。

**Comment by smuyyh** [comment]
那就是缓存策略的问题咯？Picasso会么？

**Comment by chenxiaojin** [comment]
@smuyyh 可能是。Picasso好像不会， 以前我用的是另外一个图片选择器, 用的Picasso, 但是加载速度太慢了。 Glide是很快， 但感觉要用好好难啊

**Comment by smuyyh** [comment]
感觉Fresco 比这两个都快多了。比较坑的就是它不是ImageView...   实在不行可以试试这个。

**Comment by chenxiaojin** [comment]
@smuyyh fresco感觉太难用了， 我项目最近才用个，用不习惯。 我现在用fresco去实现,  速度不是很快，比不上Glide,  只能先用着了, 后面有时间再研究了。
