### ISSUE TITLE
启用裁剪后onActivityResult怎么得到图片的数据进行上传或本地保存？

### ISSUE THREAD

**Issue by jayliang701** [smuyyh/ImageSelector#61]
如题。

没有看到关于处理裁剪图片结果相关的说明，断点在onActivityResult方法，里面的Intent对象似乎没有图片的数据或路径。

请指教。

**Comment by smuyyh** [comment]
跟正常图片选取是一样的。取list.get(0)

**Comment by jayliang701** [comment]
断点了，list有一个元素，却是 null


然后我尝试了把needCrop关闭，是可以得到路径的。开启 就不行。

**Comment by smuyyh** [comment]
<img width="859" alt="wx20170417-153325 2x" src="https://cloud.githubusercontent.com/assets/15133565/25082405/36753d32-2383-11e7-91f7-bb0ab99f8e41.png">

没发现存在这个问题，你用的是哪个版本号的？

**Comment by jayliang701** [comment]
compile 'com.yuyh.imgsel:library:1.3.8'

compileSdkVersion 25
minSdkVersion 16
targetSdkVersion 25


测试机型：小米pad
安卓4.4.4

**Comment by smuyyh** [comment]
有试过demo么？ 我这面试了一下  是可以正常获取的。

**Comment by jayliang701** [comment]
![qq20170417152959](https://cloud.githubusercontent.com/assets/8044568/25082670/e656c3be-2384-11e7-9518-cbd986d9378f.png)

**Comment by smuyyh** [comment]
AS 你可以直接点到库里面进去断点。断点一下我刚截给你的那几个位置。

**Comment by jayliang701** [comment]
你的demo是正常的~~~
还有什么可能的原因造成这个问题呢？

**Comment by smuyyh** [comment]
这个我也不确定..
