### ISSUE TITLE
三星手机拍照完成后截图屏幕旋转   就直接退出了

### ISSUE THREAD

**Issue by lixianda000** [smuyyh/ImageSelector#70]
测试机三星note3

**Comment by smuyyh** [comment]
贴一下log

**Comment by invokerhaung** [comment]
这个问题是因为横竖屏导致你原来的Activity重新执行onCreate 原来保存在该页面的值为null后会崩溃，解决办法，设置你原来activity 清单文件 android:configChanges="orientation|keyboardHidden|screenSize"
