### ISSUE TITLE
Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by loperSeven** [smuyyh/ImageSelector#71]
找不到 android.support.FILE_PROVIDER_PATHS 1.3.8版本会存在   1.3.6版本不会存在  但是1.3.6会存在冲突，希望博主轮主查找一下原因

**Comment by loperSeven** [comment]
1.3.8版本会存在

**Comment by Eklett** [comment]
1.3.8建议provider_paths.xml加个前缀,  有冲突
