### ISSUE TITLE
与bugly升级sdk 还是有Provider冲突

### ISSUE THREAD

**Issue by yujin4733** [smuyyh/ImageSelector#74]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.test.demo.fileProvider) from AndroidManifest.xml:84:13-67
	is also present at [com.yuyh.imgsel:library:1.3.8] AndroidManifest.xml:25:13-60 value=(com.test.demo.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:82:9-91:20 to override.

**Comment by smuyyh** [comment]
是有两个同名的Provider？
