### ISSUE TITLE
多选先拍照 然后就没办法选择多张了

### ISSUE THREAD

**Issue by wenzi5519** [smuyyh/ImageSelector#77]
我看代码 多选强制更改为单选是为什么呢
如果这样的话
我多选状态下 先拍照 然后在选择照片 拍照的照片就没有了
而且因为拍照路径的问题 
读不到你拍照的照片

**Comment by smuyyh** [comment]
当时这个没处理好，本来是想因为拍完照就不好继续选择图片了。

**Comment by smuyyh** [comment]
已修复
