### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by JDDJJ** [smuyyh/ImageSelector#8]
1、多选图片 有闪屏现象 其他图片框会重新刷新一下
2、4.4SDK照相有崩溃现象 跳转照相 和回调4.4 和4.4之后有区别 需要做兼容处理

**Comment by smuyyh** [comment]
好的~  我处理一下。THX

**Comment by hao8023** [comment]
你好，模拟器真机测试，打开选择页面没有图片显示出来 ，但是有占位，用的是 毕加索，请问设置有错吗？demo 可以正常显示
![Uploading `QQ图片20160917214527.png…]()


// 自定义图片加载器
				ImageLoader loader = new ImageLoader() {
					@Override
					public void displayImage(Context context, String path, ImageView imageView) {
						Picasso.with(PersonActivity.this).load(path).into(imageView);
					}
				};
// 自由配置选项
				ImgSelConfig config = new ImgSelConfig.Builder(loader)
						// 是否多选
						.multiSelect(false)
						// 确定按钮背景色
						.btnBgColor(Color.GRAY)
						// 确定按钮文字颜色
						.btnTextColor(Color.BLUE)
						// 使用沉浸式状态栏
						.statusBarColor(Color.parseColor("#3F51B5"))
						// 返回图标ResId
						.backResId(android.support.v7.appcompat.R.drawable.abc_ic_ab_back_mtrl_am_alpha)
						.title("图片")
						.titleColor(Color.WHITE)
						.titleBgColor(Color.parseColor("#3F51B5"))
						.cropSize(1, 1, 200, 200)
						.needCrop(false)
						// 第一个是否显示相机
						.needCamera(true)
						// 最大选择图片数量
						.maxNum(9)
						.build();

				ImgSelActivity.startActivity(this, config, REQUEST_CODE);


`

thanx

**Comment by hao8023** [comment]
![qq 20160917214527](https://cloud.githubusercontent.com/assets/19222430/18608597/5f7d3c20-7d20-11e6-8721-aae038620331.png)

**Comment by smuyyh** [comment]
@hao8023 配置看起来没错。Glide可以么？或者在Picasso那句打个log，看path是否正确~
