### ISSUE TITLE
当用户相册里面有大量GIf图的时候导致OOM

### ISSUE THREAD

**Issue by LiYuXx** [smuyyh/ImageSelector#80]
应该没几个用户会触发这个bug吧。但是我经常刷煎蛋留了很多搞笑的gif，做图片上传的时候，点击煎蛋缓存的文件夹，大量gif导致OOM了，是否可以设置将gif排除或者用什么办法解决这个问题

**Comment by smuyyh** [comment]
你用的版本号是什么？1.3.8我看了一下 实际上是还有去除 .gif 后缀的。

**Comment by LiYuXx** [comment]
我用的就是最新版1.3.8，用Glide加载图片,后面没问题了,我也不知道那次怎么我能进入煎蛋文件夹,没发重现了,我确定我没眼花！谢谢你贡献这么好的项目

**Comment by smuyyh** [comment]
那就尴尬了~~   有问题再说，到时再优化优化
