### ISSUE TITLE
如何清理缓存？

### ISSUE THREAD

**Issue by max8888888** [smuyyh/ImageSelector#83]
我发现了一个问题，我在应用里打开图片选择器，发现有些图片已经被删除掉了，但是还是能看到缩略图，或者有一张白色的图片占位，点击也看不到大图。但是能显示在图片列表里，也能选择并返回。返回后，这张图片就会报错，无法找到该图片。有没有方法初始化时，清理下缓存，重新扫描所有存在的图片？

**Comment by max8888888** [comment]
用demo做了下测试，发现demo也会加载那些空白预览图。能不能判断下：如果图片不存在，就不要在预览图里显示了。

**Comment by smuyyh** [comment]
是直接图片文件不存在对吧？ 好  抽时间加上
