### ISSUE TITLE
大神好，发现一个问题！

### ISSUE THREAD

**Issue by ootypoo** [smuyyh/ImageSelector#84]
如果选择的图片尺寸很小，就不会拉伸充满屏幕，感觉很难操作！

**Comment by ootypoo** [comment]
还有图片在裁剪的时候，我缩小范围，原图就会变大，有点难操作

**Comment by smuyyh** [comment]
图片裁剪目前是调用系统的裁剪    后期有时间会加入自定义裁剪功能！
