### ISSUE TITLE
请问 我现在出现个活动跳转imageview不显示的问题，求解

### ISSUE THREAD

**Issue by whtk** [smuyyh/ImageSelector#85]
我有个activity1里有个imageview  我在另外一个activity2里进行打开操作，当我把图片路径传到第一个activity1进行显示的时候（自己加了intent跳转），imageview总也显示不出来，log显示已经取到了路径了（用的eventbus），我看例子默认是自己的这个活动，我又进行了更改在activity2里有个imageview 按您的例子，结果就可以显示出来，求教为啥跳转后显示不出图片

**Comment by smuyyh** [comment]
不太明白你的意思，读取到路径的时候可以顺便判断一下文件是否存在，如果存在的话还加载不出来，那就应该跟这个库没什么关系了吧。

**Comment by whtk** [comment]
不好意思，我理解错误，sorry，关闭吧
