### ISSUE TITLE
拍照问题

### ISSUE THREAD

**Issue by shiguangxiang** [smuyyh/ImageSelector#86]
拍照的时候是正常的，到裁剪的时候照片就旋转了90度，请问一下这个咋么解决？

**Comment by smuyyh** [comment]
三星手机？

**Comment by shiguangxiang** [comment]
是的，目前这个问题是在三星手机上发现的，别的手机还没有试过！

**Comment by smuyyh** [comment]
#76 这个好像是三星本身的问题，因为裁剪调用的是系统的裁剪，后期抽空加入自定义裁剪，这是目前网上看的解决方式。

**Comment by shiguangxiang** [comment]
好的，谢谢了🙏
