### ISSUE TITLE
多选适配失效

### ISSUE THREAD

**Issue by luciandun** [smuyyh/ImageSelector#87]
issue1:当配置了相机同时配置了多选，先多选带回图片没问题，然后再次进入拍照带回图片后再次进入，发现多选功能被禁止了，标题右边的数量也不见了
issue2:statusBarColor设置后无效，任然是黑色的，在华为mate7上是这样的，系统6.0。似乎TitleBar不是ToolBar导致？
建议：标题右边button换成TextView,底部文件夹选择弄成半透明背景，选中标记可配置。
这个很棒，找了很多就这一个功能满足需求且集成简单，赞~

**Comment by smuyyh** [comment]
1：之前选择拍照默认就变为单选，方案可能有问题，后续再优化
2：华为rom的状态栏适配比较特殊，抽空会单独适配

**Comment by luciandun** [comment]
可以配置直接打开相机吗？

**Comment by smuyyh** [comment]
目前不支持。 后面我会抽空改一下

**Comment by smuyyh** [comment]
已加入直接打开相机。
