### ISSUE TITLE
进入相册为什么是白色的，看不到图片

### ISSUE THREAD

**Issue by tanghongjie** [smuyyh/ImageSelector#88]
进入相册为什么是白色的，看不到图片，要什么API才可以看的到图啊，作者

**Comment by smuyyh** [comment]
白色的？看不到图片？就是获取不到图片列表？

**Comment by shnanshan** [comment]
我用1.3.8, 打开列表后,看不到图片, 非要点击一个图片,裁剪的时候才显示

**Comment by shnanshan** [comment]
解决了.  ImageLoader 写错了
