### ISSUE TITLE
经常报NullPointerException 是怎么回事？

### ISSUE THREAD

**Issue by qwer472641940** [smuyyh/ImageSelector#89]
下面是错误日志：
java.lang.NullPointerException
 java.lang.RuntimeException:Unable to start activity ComponentInfo{包名/com.yuyh.library.imgsel.ImgSelActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.yuyh.library.imgsel.ImgSelConfig.allImagesText' on a null object reference
--

**Comment by zhangchunbin** [comment]
这个问题我也遇到了，经我研究，是因为ImgSelActivity销毁的时候没有保存配置信息。我的不完美的解决办法是这样的。//activity销毁之前保存选择相册的配置信息，防止静态变量数据丢失
    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        //这里保存Serializable(序列化)后的config对象
        outState.putSerializable("config",config);
    }
    //activity恢复的时候恢复保存的数据
    @Override
    public void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        ////这里恢复config对象
        config= (ImgSelConfig) savedInstanceState.getSerializable("config");
    }

我这样虽然解决了空指针异常，但是却带来了新的序列化问题。这个我还现在没解决。还在努力寻找办法。。。

**Comment by feisher** [comment]
同样遇到了此空指针问题，我很方

**Comment by zhangchunbin** [comment]
我也很方，楼主应该出面解决这个问题，这个轮子问题有点多

**Comment by againstsky** [comment]
gg 我刚用这个轮子，听你们这么说，我有点怕怕

**Comment by smuyyh** [comment]
最近太忙了  一直没时间弄这个    晚上优化了下，jcenter好像挂了没法登陆，明天就更新下仓库。
