### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by LinXiaoTao** [smuyyh/ImageSelector#9]
* 从媒体库获取图，要考虑分页问题
* 图片可以考虑加个大图预览功能

**Comment by smuyyh** [comment]
这个可以有~~  THX

**Comment by LinXiaoTao** [comment]
我现在也在做个图片选择器，有些问题一起探讨下。
1. 图片大小问题,是不是应该把缩略图也拿出来
2. 图片裁剪问题,如果将原图直接载入ucrop,内存占用会暴涨.多图不裁剪,应该怎么解决大小问题

**Comment by smuyyh** [comment]
1. 我试过显示缩略图，如果用Bitmap压缩，效率很低，会卡...
2. uCrop这个库还没用过~  只裁剪一张应该没什么大问题吧？

**Comment by LinXiaoTao** [comment]
1.你所说的卡是用同步方式去获取的缩略图吗？

**Comment by smuyyh** [comment]
异步。但是如果有notifyDataSetChanged操作，就会有点卡~  其他方式我暂时没去尝试

**Comment by LinXiaoTao** [comment]
可以使用DiffUtil去做局部更新
我将我做的部分上传了，有时间帮我看下，提下建议
[LPick](https://github.com/LinXiaoTao/LPick)

**Comment by smuyyh** [comment]
好的~  我先star下
