### ISSUE TITLE
关于点击拍照是就Crash的问题

### ISSUE THREAD

**Issue by xuehanhaha** [smuyyh/ImageSelector#90]
我的手机主用的SD Card，点击拍照按钮时程序会Crash掉。通过调查发现是FileProvider的问题，于是在provider_paths.xml中添加了<root-path name="root_path" path="."/>之后，就好用了，但是原理我还不太明白。

**Comment by smuyyh** [comment]
这个我不是已经添加过了么

**Comment by Lindroy** [comment]
具体怎么操作，能详细说说吗？

**Comment by Lindroy** [comment]
找到原因了，我在清单文件中的权限是这样写的:`android:authorities="com.mit.community.fileprovider"`，而ImgSelFragment中是这样的:`Uri` uri = FileProvider.getUriForFile(getActivity(),FileUtils.getApplicationId(getActivity()) + ".provider", tempFile);`。所以我只好把清单文件中的fileprovider改成provider了。

**Comment by smuyyh** [comment]
好吧..

**Comment by Lindroy** [comment]
感觉这样会跟其它的第三库冲突，不知道可不可以提供修改的方法？
