### ISSUE TITLE
图片显示不出来

### ISSUE THREAD

**Issue by luncang** [smuyyh/ImageSelector#94]
不行啊，加载不出来图片，一下是配置
` 
---------------------------

loader =((context, path, imageView) ->{
            Glide.with(UploadProductInformationActivity.this).load(path).into(imageView);
        }  );

        imgSelConfig = new ImgSelConfig.Builder(this,loader)
                // 是否多选, 默认true
                .multiSelect(true)
                // 是否记住上次选中记录, 仅当multiSelect为true的时候配置，默认为true
                .rememberSelected(true)
                // “确定”按钮背景色
                .btnBgColor(Color.GRAY)
                // “确定”按钮文字颜色
                .btnTextColor(Color.WHITE)
                // 使用沉浸式状态栏
                .statusBarColor(Color.BLACK)
                // 返回图标ResId
                .backResId(android.support.v7.appcompat.R.drawable.abc_ic_ab_back_mtrl_am_alpha)
                // 标题
                .title("图片")
                // 标题文字颜色
                .titleColor(Color.WHITE)
                // TitleBar背景色
                .titleBgColor(Color.BLACK)
                // 裁剪大小。needCrop为true的时候配置
                .cropSize(1, 1, 200, 200)
                .needCrop(true)
                // 第一个是否显示相机，默认true
                .needCamera(true)
                // 最大选择图片数量，默认9
                .maxNum(6)
                .build();`

这下面是效果：[http://static.zybuluo.com/charles-lun/1xlbnxmsiyq0hgm99kyk87pw/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20170928144346.jpg](url)

**Comment by smuyyh** [comment]
不会是gif吧？
